### ISSUE TITLE
微博分享集成问题

### ISSUE THREAD

**Issue by 756718646** [umeng/UMAndroidSdkDemo#10]
我下载demo,运行,分享成功.

然后我把微博的分享WBShareActivity删除,并把WBShareActivity在xml配置删除,clean工程,微博还能分享成功...很奇怪

我自己创建新工程,分享集成,其他都成功,就是微博分享闪退,提示

android.content.ActivityNotFoundException: Unable to find explicit activity class {com.umeng.soexample/com.umeng.socialize.media.WBShareCallBackActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                         at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1977)
                                                                         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1636)
                                                                         at android.app.Activity.startActivityForResult(Activity.java:4762)
                                                                         at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                                         at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                                                                         at android.app.Activity.startActivityForResult(Activity.java:4702)
                                                                         at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
                                                                         at android.app.Activity.startActivity(Activity.java:5123)
                                                                         at android.app.Activity.startActivity(Activity.java:5091)
                                                                         at com.umeng.socialize.handler.SinaSsoHandler.share(SinaSsoHandler.java:332)
                                                                         at com.umeng.socialize.a.a.a(Unknown Source:416)
                                                                         at com.umeng.socialize.UMShareAPI$4.a(Unknown Source:50)
                                                                         at com.umeng.socialize.UMShareAPI$4.doInBackground(Unknown Source:0)
                                                                         at com.umeng.socialize.common.QueuedWork$UMAsyncTask$1.run(QueuedWork.java:141)
                                                                         at java.lang.Thread.run(Thread.java:784)

我用旧版本集成微博是没有问题,新版本出出现这个.
我在现在这个githubdemo上,删除微博的WBShareActivity,竟然还能分享成功?

请问一下,是集成文档上面哪一步写漏了吗,还是怎么?

**Comment by 756718646** [comment]
搞错了,没问题了
