### ISSUE TITLE
友盟推送 设置 umeng_push_notification_default_small_icon bug问题

### ISSUE THREAD

**Issue by 756718646** [umeng/UMAndroidSdkDemo#11]
在帮助文档中,说明umeng_push_notification_default_small_icon在资源文件中添加,应该会那app的id,但是我现在资源文件放入了这个,但是还是提示报错了

com.umeng.soexample E/com.umeng.message.common.c: getRes(null,umeng_push_notification_default_small_icon)

com.umeng.soexample E/com.umeng.message.common.c: getRes(null,umeng_push_notification_default_large_icon)

java.lang.IllegalArgumentException: ResClass is not initialized. Please make sure you have added neccessary resources. Also make sure you have com.umeng.soexample.R$* configured in obfuscation. field=umeng_push_notification_default_large_icon

01-03 22:27:34.135 3260-4603/com.umeng.soexample W/System.err:     at com.umeng.message.common.c.a(Res.java:221)
01-03 22:27:34.135 3260-4603/com.umeng.soexample W/System.err:     at com.umeng.message.common.c.d(Res.java:150)
01-03 22:27:34.135 3260-4603/com.umeng.soexample W/System.err:     at com.umeng.message.UmengMessageHandler.getLargeIcon(UmengMessageHandler.java:468)
01-03 22:27:34.135 3260-4603/com.umeng.soexample W/System.err:     at com.umeng.message.UmengMessageHandler.a(UmengMessageHandler.java:405)
01-03 22:27:34.136 3260-4603/com.umeng.soexample W/System.err:     at com.umeng.message.UmengMessageHandler.dealWithNotificationMessage(UmengMessageHandler.java:130)
01-03 22:27:34.136 3260-4603/com.umeng.soexample W/System.err:     at com.umeng.message.UmengMessageHandler.handleMessage(UmengMessageHandler.java:62)
01-03 22:27:34.136 3260-4603/com.umeng.soexample W/System.err:     at com.umeng.message.UmengMessageCallbackHandlerService.onHandleIntent(UmengMessageCallbackHandlerService.java:170)
01-03 22:27:34.136 3260-4603/com.umeng.soexample W/System.err:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
01-03 22:27:34.136 3260-4603/com.umeng.soexample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-03 22:27:34.136 3260-4603/com.umeng.soexample W/System.err:     at android.os.Looper.loop(Looper.java:150)
01-03 22:27:34.136 3260-4603/com.umeng.soexample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
01-03 22:27:34.171 3260-4606/com.umeng.soexample D/com.umeng.message.UmengMessageCallbackHandlerService: processName=com.umeng.soexample

**Comment by captain-miao** [comment]
不知道坑了多少开发者，稍微多说一加可以免去多少时间浪费～

 ### 提示资源文件找不到？
>Android Studio开发工具是基于gradle的配置方式，资源文件的包和应用程序的包是可以分开的，为了正确的找到资源包名，为开发者提供了自定义的设置资源包的接口。当资源包名和应用程序包名不一致时，调用设置资源包名的接口：
mPushAgent.setResourcePackageName(String packageName);
————————————————
版权声明：本文为CSDN博主「ddnosh」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
[原文链接](https://blog.csdn.net/ddnosh/java/article/details/89405503)
```
PushAgent mPushAgent = PushAgent.getInstance(MyApplication.app);
mPushAgent.setResourcePackageName(xxxxx);
```
## 其实看评论才是答案
>pushAgent.setResourcePackageName(packageName)
这里packageName应该使用AndroidManifest.xml中package所对应内容，而不是BuidConfig.APPLICATION_ID。 应使用资源文件包名，而非应用程序包名。


## 错误信息引导给定的链接，啥问题解决不了：

后台显示送达，却没有弹出通知。详见问题链接 https://developer.umeng.com/docs/66632/detail/67146?um_channel=sdk
>
问题描述
显示送达，却没有弹出通知？

解决方案：
1、请检查手机设置，确保允许app弹出通知。

2、是否调用了PushAgent的setPushIntentServiceClass方法，如果调用了，需自己写代码实现通知的弹出。
